const pics=["./assets/cutecindy.jpg","./assets/pic.png"]
const pics2=['https://www.bostonherald.com/wp-content/uploads/2020/09/patsnl35.jpg?w=430',
             'https://lh3.googleusercontent.com/proxy/Jk9TlkWonDjPM3-0ej_fWogaOCWkO_fZr96Epo9d9r1on9RdOGlOd9YDQXeh65MBfXvALMeEzI2rlAJaMtMkgBha_Yw62_S0GIN53rQdyx3DFMl5CbUeegX8emvMA5A_HekEoWwwL8ZKJMAyQCs1XGO-aROOs2dZ6ssQRTwi_KargghfG5k5bLTDEoe8R0t_LLgZZiwUe5loemmfrhcym6JVH8LEwSNrj__ex1G_xCdN']
const buttons = [
    {
        name:"Height",
        property:"height",
        min:0,
        max:100,
    },
    {
        name:"Width",
        property:"width",
        min:0,
        max:100,
    },
    {
        name:"Background\nColor",
        property:"background-color",
        min:0,
        max:10,
    },
    {
        name:"Border",
        property:"border-radius",
        min:0,
        max:50,
    },
    {
        name:"Sepia",
        property:"sepia",
        min:0,
        max:100,
    },
    {
        name:"Saturation",
        property:"saturate",
        min:0,
        max:200,
    },
    {
        name:"Blur",
        property:"blur",
        min:0,
        max:20,
    },
    {
        name:"Rotate",
        property:"rotate",
        min:0,
        max:360,
    },
    {
        name:"Contrast",
        property:"contrast",
        min:0,
        max:200,
    },
    {
        name:"Brightness",
        property:"brightness",
        min:0,
        max:100,
    },

]